server:
  port: 8080
spring:
  application:
    name: leyou-item-service
  datasource:
    url: jdbc:mysql://localhost:3306/leyou
    username: root
    password: root
eureka:
  client:
    service-url:
      defautZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

mapper:
  identity: MYSQL
  not-empty: false

#显示sql语句
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl