server:
  port: 10010

spring:
  application:
    name: leyou-geteway
eureka:
  client:
    service-url:
      defautZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
zuul:
  prefix: /api
  routes:
    item-service: /item/**